images_src{1} = images_loaded{1} .* (1 - A) + ...
            ((0.9 .* images_loaded{12} + 0.1 .* images_loaded{1}) .* A);
images_src{1} = images_src{1} .* (1 - B) + ...
            ((0.7 .* images_loaded{12} + 0.3 .* images_src{1}) .* B);
        
images_src{2} = images_loaded{2} .* (1 - A) + ...
            ((0.5 .* images_loaded{5} + 0.5 .* images_loaded{2}) .* A);
images_src{2} = images_src{2} .* (1 - B) + ...
            ((0.7 .* images_loaded{4} + 0.3 .* images_src{2}) .* B);
    
images_src{3} = images_loaded{3} .* (1 - A) + ...
            ((0.7 .* images_loaded{5} + 0.3 .* images_loaded{3}) .* A);
images_src{3} = images_src{3} .* (1 - B) + ...
            ((0.7 .* images_loaded{4} + 0.3 .* images_src{3}) .* B);
        
images_src{4} = images_loaded{4} .* (1 - A) + ...
            ((0.7 .* images_loaded{8} + 0.3 * images_loaded{9}) .* A);
images_src{4} = images_src{4} .* (1 - B) + ...
            ((0.7 .* images_loaded{8} + 0.3 * images_loaded{9}) .* B);

images_src{5} = images_loaded{5} .* (1 - A) + ...
            ((0.9 .* images_loaded{3} + 0.1 .* images_loaded{5}) .* A);
images_src{5} = images_src{5} .* (1 - B) + ...
            ((0.7 .* images_loaded{3} + 0.3 .* images_src{5}) .* B);
        
images_src{6} = images_loaded{6} .* (1 - A) + ...
            ((0.9 .* images_loaded{7} + 0.1 .* images_loaded{6}) .* A);
images_src{6} = images_src{6} .* (1 - B) + ...
            ((0.8 .* images_loaded{2} + 0.2 .* images_loaded{9}) .* B);
        
images_src{7} = images_loaded{7} .* (1 - A) + ...
            ((0.9 .* images_loaded{6} + 0.1 .* images_loaded{17}) .* A);
images_src{7} = images_src{7} .* (1 - B) + ...
            ((0.8 .* images_loaded{6} + 0.2 .* images_loaded{17}) .* B);
        
images_src{8} = images_loaded{8} .* (1 - A) + ...
            ((0.8 .* images_loaded{3} + 0.2 .* images_loaded{17}) .* A);
 images_src{8} = images_src{8} .* (1 - B) + ...
             ((0.8 .* images_loaded{3} + 0.2 .* images_loaded{17}) .* B);
        
images_src{9} = images_loaded{9} .* (1 - A) + ...
            ((0.8 .* images_loaded{16} ) .* A);
 images_src{9} = images_src{9} .* (1 - B) + ...
             ((0.8 .* images_loaded{16}) .* B);
       
images_src{10} = images_loaded{10} .* (1 - A) + ...
            ((0.4 .* images_loaded{4} ) .* A);
 images_src{10} = images_src{10} .* (1 - B) + ...
             ((0.5 .* images_loaded{4}) .* B);
        
images_src{11} = images_loaded{11} .* (1 - A) + ...
            ((0.4 .* images_loaded{4} ) .* A);
 images_src{11} = images_src{11} .* (1 - B) + ...
             ((0.5 .* images_loaded{4}) .* B);       
 
images_src{12} = images_loaded{12} .* (1 - A) + ...
            ((0.8 .* images_loaded{3} + 0.3 .* images_loaded{17}) .* A);
 images_src{12} = images_src{12} .* (1 - B) + ...
             ((0.8 .* images_loaded{8} + 0.2 .* images_loaded{12}) .* B); 
        
images_src{13} = images_loaded{13} .* (1 - A) + ...
            ((0.7 .* images_loaded{15} + 50) .* A);
 images_src{13} = images_src{13} .* (1 - B) + ...
             ((0.9 .* images_loaded{15} - 50 ) .* B);
        
images_src{14} = images_loaded{14} .* (1 - A) + ...
            ((0.7 .* images_loaded{15} + 50) .* A);
 images_src{14} = images_src{14} .* (1 - B) + ...
             ((0.9 .* images_loaded{15} - 50 ) .* B);
        
images_src{15} = images_loaded{15} .* (1 - A) + ...
            ((0.7 .* images_loaded{15} + 50) .* A);
 images_src{15} = images_src{15} .* (1 - B) + ...
            ((0.9 .* images_loaded{15} - 30 ) .* B);
        
images_src{16} = images_loaded{16} .* (1 - A) + ...
            ((0.8 .* images_loaded{9} + 30) .* A);
images_src{16} = images_src{16} .* (1 - B) + ...
            ((0.8 .* images_loaded{9} + 40) .* B);

images_src{17} = images_loaded{17} .* (1 - A) + ...
            (( images_loaded{9}) .* A);
images_src{17} = images_src{17} .* (1 - B) + ...
            ((images_loaded{11}) .* B);
     
images_src{18} = images_loaded{18} .* (1 - A) + ...
            ((0.9 .* images_loaded{14} + 0.1 .* images_loaded{18}) .* A);
images_src{18} = images_src{18} .* (1 - B) + ...
            ((1 .* images_loaded{2} - 18) .* B);
        
images_src{19} = images_loaded{19} .* (1 - A) + ...
            ((0.7 .* images_loaded{3} + 0.1 .* images_loaded{18}) .* A);
images_src{19} = images_src{19} .* (1 - B) + ...
            ((0.9 .* images_loaded{3} + 0.1 .* images_loaded{18}) .* B);

images_src{20} = images_loaded{20} .* (1 - A) + ...
            ((0.7 .* images_loaded{3} + 0.1 .* images_loaded{20}) .* A);
images_src{20} = images_src{20} .* (1 - B) + ...
            ((0.9 .* images_loaded{2}) .* B);

images_src{21} = images_loaded{21} .* (1 - A) + ...
            ((0.7 .* images_loaded{3} + 0.1 .* images_loaded{20}) .* A);
images_src{21} = images_src{21} .* (1 - B) + ...
            ((0.9 .* images_loaded{2}) .* B);
        
images_src{22} = images_loaded{22} .* (1 - A) + ...
            ((0.7 .* images_loaded{3} + 0.1 .* images_loaded{20}) .* A);
images_src{22} = images_src{22} .* (1 - B) + ...
            ((0.9 .* images_loaded{2}) .* B);

images_src{23} = images_loaded{23} .* (1 - A) + ...
            ((0.7 .* images_loaded{3} + 0.1 .* images_loaded{20}) .* A);
images_src{23} = images_src{23} .* (1 - B) + ...
            ((0.9 .* images_loaded{2}) .* B);
        

images_src{24} = images_loaded{24} .* (1 - A) + ...
            ((1 .* images_loaded{1} ) .* A);
images_src{24} = images_src{24} .* (1 - B) + ...
            ((1 .* images_loaded{12}) .* B);
        
images_src{25} = images_loaded{25} .* (1 - A) + ...
            ((1 .* images_loaded{1}) .* A);
images_src{25} = images_src{25} .* (1 - B) + ...
            ((1 .* images_loaded{12}) .* B);
         
images_src{26} = images_loaded{26} .* (1 - A) + ...
            ((1 .* images_loaded{1} ) .* A);
images_src{26} = images_src{26} .* (1 - B) + ...
            ((1 .* images_loaded{1}) .* B);